# Generated by Django 3.2.8 on 2021-10-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='author', max_length=255),
        ),
    ]
