# Generated by Django 3.2.8 on 2021-10-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_article_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('HOM', 'Home'), ('FOO', 'Food'), ('FAS', 'Fashion'), ('LOC', 'Local'), ('GLO', 'Global')], default='HOM', max_length=3),
        ),
    ]
